### PR TITLE
Always show deploy option

### PR DESCRIPTION
**Pull request by TanmayaA**
This PR removes the check to show the deploy button only if there is a diff between deployed code and the git repo. 
This check didn't consider other possible conditions needing a re-deploy, even when there is no change in deployed app code base.
Changes in chef code base, base instances change etc, are a few such cases.

### CODE REVIEW

**Comment by hayate** [comment]
@TanmayaA could you please add a little background description/explanation to this PR.

**Comment by seikoudoku2000** [comment]
LGTM

**Comment by toshipon** [comment]
LGTM

**Comment by hayate** [comment]
:+1: LGTM

**Comment by seikoudoku2000** [comment]
@TanmayaA Is this ready to merge?  Please remove `[WIP]` when ready.

**Comment by TanmayaA** [comment]
@seikoudoku2000 I didn't realize the WIP tag is still there. This has been running on staging goship for some time now, hence removing WIP.

**Comment by seikoudoku2000** [comment]
Thank you!

**Pull request merged**
